site_name: dib-lab NSURP project
site_url: http://bluegenes.github.io/2020-NSURP/
repo_name: 2020-NSURP
repo_url: https://github.com/bluegenes/2020-NSURP
edit_uri: ""

copyright: 'Copyright &copy; 2020 <a href="http://ivory.idyll.org/lab/">Lab for Data Intensive Biology</a> at UC Davis'

# change directory names here
docs_dir: doc
site_dir: site

theme:
  name: material

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'deep purple'
    accent: 'indigo'
  
  # fun logos! see https://material.io/icons/
  icon:
    logo: material/dns

  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  
# optionally give a title for each page or section
nav:
  - 'Home': 'index.md'
  - 'Getting Started': '00.getting-started.md'
  - "Setting up Farm": 01.using-farm.md"
  - "Using Conda": "02.conda.md"
  - "Keeping a Lab Notebook": "03.lab-notebook.md"
